### ISSUE TITLE
Stablish uni-directional SFP network link

### ISSUE THREAD

**Issue by alireza11048** [xcp-ng-rpms/intel-ixgbe#1]
Hi,
I am trying to establish a uni-directional Ethernet link where a singular fiber is used to transmit data to the receiver where both sides use ixgbe as driver. The Rx of the transmit side and the Tx of the receive side are not physically connected, like in a Data diode scenario. The problem is, as soon as I detach the tx line from one side, both side link status goes DOWN. is it possible to mask link status in the ixgbe driver?

**Comment by stormi** [comment]
Hi. We ship the driver as provided by Intel, so we likely won't handle such changes at our level.

**Comment by stormi** [comment]
You may try our forum to see if other users have solutions, or one of our developers has an idea: https://xcp-ng.org/forum/
